package clr

type SystemType struct {
	vtbl *SystemType_Vtbl
}

type SystemType_Vtbl struct {
	QueryInterface uintptr
	AddRef         uintptr
	Release        uintptr

	GetTypeInfoCount      uintptr
	GetTypeInfo           uintptr
	GetIDsOfNames         uintptr
	Invoke                uintptr
	ToString              uintptr
	Equals                uintptr
	GetHashCode           uintptr
	GetType               uintptr
	MemberType            uintptr
	name                  uintptr
	DeclaringType         uintptr
	ReflectedType         uintptr
	GetCustomAttributes   uintptr
	GetCustomAttributes_2 uintptr
	IsDefined             uintptr
	Guid                  uintptr
	Module                uintptr
	Assembly              uintptr
	TypeHandle            uintptr
	FullName              uintptr
	Namespace             uintptr
	AssemblyQualifiedName uintptr
	GetArrayRank          uintptr
	BaseType              uintptr
	GetConstructors       uintptr
	GetInterface          uintptr
	GetInterfaces         uintptr
	FindInterfaces        uintptr
	GetEvent              uintptr
	GetEvents             uintptr
	GetEvents_2           uintptr
	GetNestedTypes        uintptr
	GetNestedType         uintptr
	GetMember             uintptr
	GetDefaultMembers     uintptr
	FindMembers           uintptr
	GetElementType        uintptr
	IsSubclassOf          uintptr
	IsInstanceOfType      uintptr
	IsAssignableFrom      uintptr
	GetInterfaceMap       uintptr
	GetMethod             uintptr
	GetMethod_2           uintptr
	GetMethods            uintptr
	GetField              uintptr
	GetFields             uintptr
	GetProperty           uintptr
	GetProperty_2         uintptr
	GetProperties         uintptr
	GetMember_2           uintptr
	GetMembers            uintptr
	InvokeMember          uintptr
	UnderlyingSystemType  uintptr
	InvokeMember_2        uintptr
	InvokeMember_3        uintptr
	GetConstructor        uintptr
	GetConstructor_2      uintptr
	GetConstructor_3      uintptr
	GetConstructors_2     uintptr
	TypeInitializer       uintptr
	GetMethod_3           uintptr
	GetMethod_4           uintptr
	GetMethod_5           uintptr
	GetMethod_6           uintptr
	GetMethods_2          uintptr
	GetField_2            uintptr
	GetFields_2           uintptr
	GetInterface_2        uintptr
	GetEvent_2            uintptr
	GetProperty_3         uintptr
	GetProperty_4         uintptr
	GetProperty_5         uintptr
	GetProperty_6         uintptr
	GetProperty_7         uintptr
	GetProperties_2       uintptr
	GetNestedTypes_2      uintptr
	GetNestedType_2       uintptr
	GetMember_3           uintptr
	GetMembers_2          uintptr
	Attributes            uintptr
	IsNotPublic           uintptr
	IsPublic              uintptr
	IsNestedPublic        uintptr
	IsNestedPrivate       uintptr
	IsNestedFamily        uintptr
	IsNestedAssembly      uintptr
	IsNestedFamANDAssem   uintptr
	IsNestedFamORAssem    uintptr
	IsAutoLayout          uintptr
	IsLayoutSequential    uintptr
	IsExplicitLayout      uintptr
	IsClass               uintptr
	IsInterface           uintptr
	IsValueType           uintptr
	IsAbstract            uintptr
	IsSealed              uintptr
	IsEnum                uintptr
	IsSpecialName         uintptr
	IsImport              uintptr
	IsSerializable        uintptr
	IsAnsiClass           uintptr
	IsUnicodeClass        uintptr
	IsAutoClass           uintptr
	IsArray               uintptr
	IsByRef               uintptr
	IsPointer             uintptr
	IsPrimitive           uintptr
	IsCOMObject           uintptr
	HasElementType        uintptr
	IsContextful          uintptr
	IsMarshalByRef        uintptr
	Equals_2              uintptr
}
